services:
  db:
    environment:
      PGUSER: postgres
      POSTGRES_PASSWORD: local
    healthcheck:
      interval: 1s
      retries: 5
      test: ["CMD-SHELL", "pg_isready"]
      timeout: 5s
    hostname: postgres
    image: postgres:17.2
    restart: always
    shm_size: 128mb
    volumes:
      - db-data:/var/lib/postgresql/data

  db-test:
    environment:
      PGUSER: postgres
      POSTGRES_PASSWORD: local
    healthcheck:
      interval: 1s
      retries: 5
      test: ["CMD-SHELL", "pg_isready"]
      timeout: 5s
    hostname: postgres-test
    image: postgres:17.2
    profiles: ["test"]
    restart: always
    shm_size: 128mb

  web:
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URI: postgresql://postgres:local@postgres:5432/postgres
      DATABASE_URI_TEST: postgresql://postgres:local@postgres-test:5432/postgres
    image: fanchymarin/qualentum-web:latest
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - ./web/src:/app

volumes:
  db-data: