apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    name: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  ports:
    - name: web
      port: 5000
      targetPort: 5000
  selector:
    name: web
